# Your personal GitHub token
github_token: 507af26d7753a75a4a1cb649069e4e92318f2d5c
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: yii

# Virtual machine IP
ip: 10.10.20.166

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
